### ISSUE TITLE
Support Unique Devices

### ISSUE THREAD

**Issue by PierreSelim** [Commonists/pageview-api#1]
See:
* https://wikitech.wikimedia.org/wiki/Analytics/Unique_Devices#Quick_Start
* https://meta.wikimedia.org/wiki/Research:Unique_Devices
* https://wikimedia.org/api/rest_v1/metrics/unique-devices/en.wikipedia.org/all-sites/daily/20160201/20160229

**Comment by PierreSelim** [comment]
I'm wondering whether I should merge [branch `unique_devices`](https://github.com/Commonists/pageview-api/commits/unique_devices) or fork the project to increase it to a wider scope (implement all the Wikimedia API rest v1)

**Comment by JeanFred** [comment]
I’m not sure I follow you @PierreSelim − why would we want to have two projects?

**Comment by PierreSelim** [comment]
it's not really pageviews :)

**Comment by JeanFred** [comment]
Right :)

**Comment by PierreSelim** [comment]
Code is merged, so I'm closing this issue
